name: Build (Termux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  NDK_VERSION: r25c  # Compatible with API 21+ (Android 5.0+)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: aarch64-linux-android

    - name: Install Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-${{ env.NDK_VERSION }}-linux.zip
        unzip android-ndk-${{ env.NDK_VERSION }}-linux.zip
        echo "ANDROID_NDK_HOME=${PWD}/android-ndk-${{ env.NDK_VERSION }}" >> $GITHUB_ENV

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Build for arm64-v8a
      run: cargo ndk build --target aarch64-linux-android --release

    - name: Upload arm64 binary
      uses: actions/upload-artifact@v4
      with:
        name: redlib-arm64-android
        path: target/aarch64-linux-android/release/redlib
        retention-days: 30
